### ISSUE TITLE
Failed to generate JavaDoc

### ISSUE THREAD

**Issue by spinningHorse** [CMPUT301F21T20/HabitTracker#63]

**Comment by spinningHorse** [comment]
![unknown](https://user-images.githubusercontent.com/87087607/140461894-d8c8ff4b-34e8-4693-97a2-6aaed798807c.png)

**Comment by spinningHorse** [comment]
@hamzaMAlvi Please help on this problem.

**Comment by spinningHorse** [comment]
"/Applications/Android Studio.app/Contents/jre/Contents/Home/bin/javadoc" -protected -splitindex -encoding UTF-8 -sourcepath /Users/markzhang/Library/Android/sdk/platforms/android-30/android.jar -d /Users/markzhang/Projects/CMPUT301/HabitTracker/JavaDoc @/private/var/folders/p1/zzxtrsqj41ggkyt87vj4kg8r0000gn/T/javadoc_args
Loading source file /Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/controllers/HabitListController.java...
Loading source file /Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/LoginActivity.java...
Loading source file /Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/ViewHabitActivity.java...
Loading source file /Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/classes/Habit.java...
Loading source file /Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/AddNewHabitActivity.java...
Loading source file /Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/controllers/HabitController.java...
Loading source file /Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/RegisterActivity.java...
Loading source file /Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/MainActivity.java...
Loading source file /Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/classes/User.java...
Loading source file /Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/classes/HabitList.java...
Loading source file /Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/adapters/HabitListAdapter.java...
Constructing Javadoc information...
/Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/controllers/HabitListController.java:3: error: package android.util does not exist
import android.util.Log;
                   ^
/Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/controllers/HabitController.java:3: error: package android.util does not exist
import android.util.Log;
                   ^
/Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/classes/HabitList.java:3: error: package android.os does not exist
import android.os.Build;
                 ^
/Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/LoginActivity.java:6: error: package android.content does not exist
import android.content.Intent;
                      ^
/Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/LoginActivity.java:7: error: package android.os does not exist
import android.os.Bundle;
                 ^
/Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/LoginActivity.java:8: error: package android.text does not exist
import android.text.TextUtils;
                   ^
/Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/LoginActivity.java:9: error: package android.view does not exist
import android.view.View;
                   ^
/Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/LoginActivity.java:10: error: package android.widget does not exist
import android.widget.Button;
                     ^
/Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/LoginActivity.java:11: error: package android.widget does not exist
import android.widget.EditText;
                     ^
/Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/LoginActivity.java:12: error: package android.widget does not exist
import android.widget.TextView;
                     ^
/Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/LoginActivity.java:13: error: package android.widget does not exist
import android.widget.Toast;
                     ^
/Users/markzhang/Projects/CMPUT301/HabitTracker/app/src/main/java/com/example/habittracker/LoginActivity.java:20: error: cannot access ViewGroup
public class LoginActivity extends AppCompatActivity {
       ^
  class file for android.view.ViewGroup not found
javadoc: error - fatal error encountered: java.lang.NullPointerException
javadoc: error - Please file a bug against the javadoc tool via the Java bug reporting page
(http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com)
for duplicates. Include error messages and the following diagnostic in your report. Thank you.
java.lang.NullPointerException
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$MembersPhase.runPhase(TypeEnter.java:934)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$Phase.doCompleteEnvs(TypeEnter.java:282)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$MembersPhase.doCompleteEnvs(TypeEnter.java:877)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$Phase.completeEnvs(TypeEnter.java:251)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$Phase.completeEnvs(TypeEnter.java:266)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$Phase.completeEnvs(TypeEnter.java:266)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$Phase.completeEnvs(TypeEnter.java:266)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter.complete(TypeEnter.java:198)
	at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:642)
	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1326)
	at jdk.compiler/com.sun.tools.javac.comp.Enter.complete(Enter.java:583)
	at jdk.compiler/com.sun.tools.javac.comp.Enter.main(Enter.java:560)
	at jdk.javadoc/jdk.javadoc.internal.tool.JavadocEnter.main(JavadocEnter.java:79)
	at jdk.javadoc/jdk.javadoc.internal.tool.JavadocTool.getEnvironment(JavadocTool.java:206)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:576)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:432)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:345)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
14 errors

"javadoc" finished with exit code 4
